title: LearnTo iOS
description: > # this means to ignore newlines until "baseurl:"
  LearnTo iOS is an 8 week training course hosted by Charged, Secure Broadcast & NSBelfast
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/ChargedCity" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2016_style/img/icon-large.png"

social:
  name: Charged Facebook Page
  link: "https://www.facebook.com/chargedcity/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

# Google Analytics
google_analytics: UA-116567509-1

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/chargedcity/
  - title: twitter
    url: https://twitter.com/ChargedCity

# Build settings
markdown: kramdown
permalink: pretty
